class EnvironmentSettings:
    def __init__(self):
        self.workspace_dir = '/media/lisuran/OSTrack_sv'    # Base directory for saving network checkpoints.
        self.tensorboard_dir = '/media/lisuran/OSTrack_sv/tensorboard'    # Directory for tensorboard files.
        self.pretrained_networks = '/media/lisuran/OSTrack_sv/pretrained_models'
        self.lasot_dir = '/data/sot/data/lasot'
        self.sv248s_train_dir = '/media/pc-4090/9bd4d9e0-148f-4dd1-a9c6-1f4c9dff8e4e/datasets/sv248/train_sv'
        self.sv248s_train_modal_dir = '/media/pc-4090/9bd4d9e0-148f-4dd1-a9c6-1f4c9dff8e4e/datasets/sv248/train_sv'
        self.got10k_dir = '/data/sot/data/got10k/train'
        self.got10k_val_dir = '/data/sot/data/got10k/val'
        self.lasot_lmdb_dir = '/data/sot/data/lasot_lmdb'
        self.got10k_lmdb_dir = '/data/sot/data/got10k_lmdb'
        self.trackingnet_dir = '/data/sot/data/trackingnet'
        self.trackingnet_lmdb_dir = '/data/sot/data/trackingnet_lmdb'
        self.coco_dir = '/data/sot/data/coco'
        self.coco_lmdb_dir = '/data/sot/data/coco_lmdb'
        self.lvis_dir = ''
        self.sbd_dir = ''
        self.imagenet_dir = '/data/sot/data/vid'
        self.imagenet_lmdb_dir = '/data/sot/data/vid_lmdb'
        self.imagenetdet_dir = ''
        self.ecssd_dir = ''
        self.hkuis_dir = ''
        self.msra10k_dir = ''
        self.davis_dir = ''
        self.youtubevos_dir = ''
